#!/bin/sh
if [ "$(git symbolic-ref HEAD)" == "refs/heads/master" ]
then
        echo "Cannot commit to the master branch."
		echo "Please see https://piazza.com/class/hkxejwsmf0z2fe?cid=23 for homework instructions"
        echo "Remove the added files, create a homework branch and add the files there."
        exit 1

fi
